# Generated by Django 3.2.3 on 2021-06-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('title', models.CharField(db_column='Title', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(db_column='Description', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Saless',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=254, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='Year')),
                ('company', models.ForeignKey(db_column='Company', on_delete=django.db.models.deletion.DO_NOTHING, to='myFirstApp.vehicles')),
            ],
        ),
    ]
